import {z} from "zod";
export const categories=["RESCUE_EVACUATION","MEDICAL_ASSISTANCE","FOOD","DRINKING_WATER","SHELTER","ESSENTIAL_MEDICINE","VULNERABLE_SUPPORT","SANITATION","LIVESTOCK_RESCUE","ANIMAL_FEED","TRANSPORT","OTHER_URGENT"] as const;
export const requestStatuses=["NEW","UNDER_REVIEW","CALLBACK_REQUIRED","VERIFIED","UNABLE_TO_VERIFY","PRIORITISED","ORGANISATION_ASSIGNED","VOLUNTEER_ASSIGNED","ACCEPTED","EN_ROUTE","ON_SITE","ASSISTANCE_DELIVERED","VERIFICATION_PENDING","RESOLVED","REOPENED","DUPLICATE","CANCELLED","REQUESTER_UNREACHABLE","REFERRED_TO_AUTHORITY"] as const;
export type RequestStatus=typeof requestStatuses[number];
export const helpRequestSchema=z.object({language:z.enum(["as-IN","en-IN"]),category:z.enum(categories),name:z.string().trim().min(2).max(100),mobile:z.string().regex(/^\+?[0-9]{10,15}$/),district:z.string().trim().min(2).max(80),locality:z.string().trim().min(2).max(160),landmark:z.string().trim().max(200).optional(),latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional(),locationAccuracyMetres:z.number().nonnegative().max(100000).optional(),locationSource:z.enum(["GPS","MANUAL_PIN","TEXT_ONLY"]).default("TEXT_ONLY"),locationConsent:z.boolean().default(false),affectedPeople:z.coerce.number().int().min(1).max(10000),children:z.coerce.number().int().min(0).max(10000),elderly:z.coerce.number().int().min(0).max(10000),medicalEmergency:z.boolean().default(false),immediateDanger:z.boolean().default(false),evacuationRequired:z.boolean().default(false),description:z.string().trim().min(10).max(4000),consent:z.literal(true),website:z.string().max(0).optional(),idempotencyKey:z.string().uuid()}).superRefine((value,context)=>{const hasLatitude=value.latitude!==undefined,hasLongitude=value.longitude!==undefined;if(hasLatitude!==hasLongitude)context.addIssue({code:"custom",path:["latitude"],message:"Latitude and longitude must be supplied together"});if((hasLatitude||hasLongitude)&&!value.locationConsent)context.addIssue({code:"custom",path:["locationConsent"],message:"Location consent is required for coordinates"});if(value.locationSource!=="TEXT_ONLY"&&!hasLatitude)context.addIssue({code:"custom",path:["locationSource"],message:"Selected location source requires coordinates"})});
export type HelpRequestInput=z.infer<typeof helpRequestSchema>;
const allowed:Record<RequestStatus,readonly RequestStatus[]>={NEW:["UNDER_REVIEW","CANCELLED"],UNDER_REVIEW:["CALLBACK_REQUIRED","VERIFIED","UNABLE_TO_VERIFY","DUPLICATE","CANCELLED","REQUESTER_UNREACHABLE"],CALLBACK_REQUIRED:["UNDER_REVIEW","REQUESTER_UNREACHABLE","CANCELLED"],VERIFIED:["PRIORITISED","REFERRED_TO_AUTHORITY","CANCELLED"],UNABLE_TO_VERIFY:["UNDER_REVIEW","CANCELLED"],PRIORITISED:["ORGANISATION_ASSIGNED","REFERRED_TO_AUTHORITY","CANCELLED"],ORGANISATION_ASSIGNED:["VOLUNTEER_ASSIGNED","CANCELLED"],VOLUNTEER_ASSIGNED:["ACCEPTED","PRIORITISED","CANCELLED"],ACCEPTED:["EN_ROUTE","PRIORITISED","CANCELLED"],EN_ROUTE:["ON_SITE","PRIORITISED","CANCELLED"],ON_SITE:["ASSISTANCE_DELIVERED","PRIORITISED"],ASSISTANCE_DELIVERED:["VERIFICATION_PENDING","REOPENED"],VERIFICATION_PENDING:["RESOLVED","REOPENED"],RESOLVED:["REOPENED"],REOPENED:["UNDER_REVIEW"],DUPLICATE:["REOPENED"],CANCELLED:["REOPENED"],REQUESTER_UNREACHABLE:["UNDER_REVIEW","CANCELLED"],REFERRED_TO_AUTHORITY:["UNDER_REVIEW","RESOLVED"]};
export function canTransition(from:RequestStatus,to:RequestStatus){return allowed[from].includes(to)}
export function assertTransition(from:RequestStatus,to:RequestStatus){if(!canTransition(from,to))throw new Error(`Invalid request transition: ${from} -> ${to}`)}
export function createPublicReference(){const bytes=crypto.getRandomValues(new Uint8Array(8));return `FSA-${Array.from(bytes,b=>b.toString(36).padStart(2,"0")).join("").toUpperCase()}`}
