import {randomBytes} from "node:crypto";
import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {z} from "zod";
import {serverEnv} from "@/lib/env";
import {AesGcmSensitiveDataProtector} from "@/services/security/sensitive-data";

const schema=z.object({requestReference:z.string().regex(/^FSA-[A-F0-9]{16}$/),name:z.string().trim().min(2).max(100),mobile:z.string().regex(/^\+?[0-9]{10,15}$/),helpDescription:z.string().trim().min(10).max(1000),etaMinutes:z.coerce.number().int().min(1).max(1440),peopleComing:z.coerce.number().int().min(1).max(100),hasVehicle:z.boolean(),consent:z.literal(true),website:z.string().max(0).optional()});
export async function POST(request:Request){const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({ok:false,error:"INVALID_OFFER"},{status:400});if(parsed.data.website)return NextResponse.json({ok:true},{status:202});const env=serverEnv();if(!env.NEXT_PUBLIC_SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY||!env.DATA_ENCRYPTION_KEY||!env.PHONE_HASH_KEY)return NextResponse.json({ok:false,error:"SERVICE_NOT_CONFIGURED"},{status:503});const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});const {data:helpRequest}=await db.from("help_requests").select("id,status").eq("public_reference",parsed.data.requestReference).maybeSingle();if(!helpRequest||!["NEW","UNDER_REVIEW","VERIFIED","PRIORITISED","REOPENED"].includes(helpRequest.status))return NextResponse.json({ok:false,error:"REQUEST_NOT_OPEN"},{status:409});const protector=new AesGcmSensitiveDataProtector(env.DATA_ENCRYPTION_KEY,env.PHONE_HASH_KEY);const accessCode=randomBytes(9).toString("base64url");const {data,error}=await db.from("responder_offers").insert({request_id:helpRequest.id,responder_name_encrypted:protector.encrypt(parsed.data.name),phone_encrypted:protector.encrypt(parsed.data.mobile),help_description_encrypted:protector.encrypt(parsed.data.helpDescription),eta_minutes:parsed.data.etaMinutes,people_coming:parsed.data.peopleComing,has_vehicle:parsed.data.hasVehicle,contact_share_consent:true,responder_access_hash:protector.accessHash(accessCode)}).select("public_reference").single();if(error||!data)return NextResponse.json({ok:false,error:"OFFER_FAILED"},{status:503});return NextResponse.json({ok:true,offerReference:data.public_reference,accessCode},{status:201,headers:{"Cache-Control":"no-store"}})}
