"use server";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {revalidatePath} from "next/cache";
import {createClient} from "@supabase/supabase-js";
import {serverEnv} from "@/lib/env";
import {caseCookie} from "@/lib/community-access";
import {AesGcmSensitiveDataProtector} from "@/services/security/sensitive-data";

function client(){const env=serverEnv();if(!env.NEXT_PUBLIC_SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)throw new Error("Community service unavailable");return createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}})}
function protector(){const env=serverEnv();if(!env.DATA_ENCRYPTION_KEY||!env.PHONE_HASH_KEY)throw new Error("Privacy service unavailable");return new AesGcmSensitiveDataProtector(env.DATA_ENCRYPTION_KEY,env.PHONE_HASH_KEY)}
export async function openPrivateCase(formData:FormData){const reference=String(formData.get("reference")??"");const role=String(formData.get("role")??"");const code=String(formData.get("accessCode")??"");const offerReference=String(formData.get("offerReference")??"");if(!/^FSA-[A-F0-9]{16}$/.test(reference)||!code)redirect("/community");const hash=protector().accessHash(code);const db=client();if(role==="requester"){const {data}=await db.from("help_requests").select("id").eq("public_reference",reference).eq("requester_access_hash",hash).maybeSingle();if(!data)redirect(`/case/${reference}/manage?error=1`);(await cookies()).set(caseCookie(reference),`requester:${hash}`,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:`/case/${reference}`,maxAge:60*60*12});redirect(`/case/${reference}/manage`)}if(role==="responder"&&/^FSO-[A-F0-9]{12}$/.test(offerReference)){const {data}=await db.from("responder_offers").select("id,help_requests!inner(public_reference)").eq("public_reference",offerReference).eq("responder_access_hash",hash).eq("help_requests.public_reference",reference).maybeSingle();if(!data)redirect(`/case/${reference}/coordination?error=1`);(await cookies()).set(caseCookie(reference),`responder:${offerReference}:${hash}`,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:`/case/${reference}`,maxAge:60*60*12});redirect(`/case/${reference}/coordination`)}redirect(`/case/${reference}/coordination?error=1`)}
export async function acceptOffer(formData:FormData){const reference=String(formData.get("reference")??"");const offerReference=String(formData.get("offerReference")??"");const value=(await cookies()).get(caseCookie(reference))?.value;if(!value?.startsWith("requester:"))redirect(`/case/${reference}/manage`);const hash=value.slice("requester:".length);const {data,error}=await client().rpc("accept_community_offer",{p_request_reference:reference,p_offer_reference:offerReference,p_access_hash:hash});if(error||data!==true)throw new Error("Offer could not be accepted");revalidatePath(`/case/${reference}`);redirect(`/case/${reference}/coordination`)}
