"use client";

import {useEffect,useRef,useState} from "react";
import type {Map as LeafletMap,CircleMarker} from "leaflet";

type Language="as-IN"|"en-IN";
type LocationSource="GPS"|"MANUAL_PIN"|"TEXT_ONLY";
interface Position{latitude:number;longitude:number;accuracy?:number;source:LocationSource}

const copy={
  "as-IN":{title:"স্থান",intro:"আপুনি সন্মতি দিলে GPS ব্যৱহাৰ কৰক, অথবা মানচিত্ৰত আনুমানিক স্থানটো টিপক।",gps:"মোৰ বৰ্তমান স্থান ব্যৱহাৰ কৰক",locating:"স্থান বিচাৰি থকা হৈছে…",clear:"স্থান আঁতৰাওক",consent:"সাহায্য সমন্বয়ৰ বাবে অনুমোদিত আয়োজকক মোৰ সঠিক স্থান দেখুৱাবলৈ মই সন্মতি দিছোঁ।",selected:"বাছনি কৰা স্থান",manual:"মানচিত্ৰত টিপি স্থান বাছনি কৰক।",denied:"GPS স্থান পোৱা নগ'ল। মানচিত্ৰত পিন দিয়ক বা তলত স্থান লিখক।",accuracy:"GPS-ৰ সঠিকতা"},
  "en-IN":{title:"Location",intro:"With your consent, use GPS or tap the map to mark an approximate position.",gps:"Use my current location",locating:"Finding location…",clear:"Remove location",consent:"I consent to my exact location being shown to authorised organisers for relief coordination.",selected:"Selected location",manual:"Tap the map to select a location.",denied:"GPS location was unavailable. Place a pin or enter the location as text below.",accuracy:"GPS accuracy"}
} satisfies Record<Language,Record<string,string>>;

export function LocationPicker({language}:{language:Language}){const container=useRef<HTMLDivElement>(null);const map=useRef<LeafletMap|null>(null);const marker=useRef<CircleMarker|null>(null);const [position,setPosition]=useState<Position>();const [consent,setConsent]=useState(false);const [locating,setLocating]=useState(false);const [error,setError]=useState<string>();const t=copy[language];
  useEffect(()=>{let disposed=false;void import("leaflet").then(L=>{if(disposed||!container.current||map.current)return;const instance=L.map(container.current,{zoomControl:true}).setView([26.2,92.9],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:19}).addTo(instance);instance.on("click",event=>{const next={latitude:event.latlng.lat,longitude:event.latlng.lng,source:"MANUAL_PIN" as const};setPosition(next);setConsent(true);setError(undefined)});map.current=instance});return()=>{disposed=true;map.current?.remove();map.current=null}},[]);
  useEffect(()=>{void import("leaflet").then(L=>{if(!map.current)return;if(marker.current){marker.current.remove();marker.current=null}if(position){marker.current=L.circleMarker([position.latitude,position.longitude],{radius:10,color:"#056447",fillColor:"#087f5b",fillOpacity:.9,weight:3}).addTo(map.current);map.current.setView([position.latitude,position.longitude],Math.max(map.current.getZoom(),14))}})},[position]);
  function locate(){if(!navigator.geolocation){setError(t.denied);return}setLocating(true);setError(undefined);navigator.geolocation.getCurrentPosition(result=>{setPosition({latitude:result.coords.latitude,longitude:result.coords.longitude,accuracy:result.coords.accuracy,source:"GPS"});setConsent(true);setLocating(false)},()=>{setError(t.denied);setLocating(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
  return <fieldset className="stack"><legend>{t.title}</legend><p className="muted">{t.intro}</p><div className="actions"><button className="button secondary" type="button" onClick={locate} disabled={locating}>{locating?t.locating:t.gps}</button>{position&&<button className="button secondary" type="button" onClick={()=>{setPosition(undefined);setConsent(false)}}>{t.clear}</button>}</div>{error&&<p className="error" role="alert">{error}</p>}<div ref={container} className="location-map" aria-label={t.manual}/><p className="muted">{position?`${t.selected}: ${position.latitude.toFixed(5)}, ${position.longitude.toFixed(5)}${position.accuracy?` · ${t.accuracy}: ±${Math.round(position.accuracy)} m`:""}`:t.manual}</p><label><input type="checkbox" name="locationConsent" checked={consent} onChange={event=>setConsent(event.target.checked)} disabled={!position}/> {t.consent}</label><input type="hidden" name="latitude" value={position?.latitude??""}/><input type="hidden" name="longitude" value={position?.longitude??""}/><input type="hidden" name="locationAccuracyMetres" value={position?.accuracy??""}/><input type="hidden" name="locationSource" value={position?.source??"TEXT_ONLY"}/></fieldset>}
