import {cookies} from "next/headers";
import {notFound} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {openPrivateCase,acceptOffer} from "@/app/community-actions";
import {caseCookie} from "@/lib/community-access";
import {serverEnv} from "@/lib/env";
import {AesGcmSensitiveDataProtector} from "@/services/security/sensitive-data";
export const dynamic="force-dynamic";
type Offer={public_reference:string;responder_name_encrypted:string;help_description_encrypted:string;eta_minutes:number;people_coming:number;has_vehicle:boolean;status:string;created_at:string};
function configured(){const env=serverEnv();if(!env.NEXT_PUBLIC_SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY||!env.DATA_ENCRYPTION_KEY||!env.PHONE_HASH_KEY)throw new Error("Community service unavailable");return env}
export default async function ManageCase({params,searchParams}:{params:Promise<{reference:string}>;searchParams:Promise<{error?:string}>}){const {reference}=await params;if(!/^FSA-[A-F0-9]{16}$/.test(reference))notFound();const env=configured();const token=(await cookies()).get(caseCookie(reference))?.value;const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});const {data:request}=await db.from("help_requests").select("id,requester_access_hash,status").eq("public_reference",reference).maybeSingle();if(!request)notFound();if(!token?.startsWith("requester:")||token.slice(10)!==request.requester_access_hash){const {error}=await searchParams;return <div className="container responder-login"><section className="card stack"><h1>Requester private access</h1><p>Enter the private code shown when this request was submitted.</p>{error&&<p className="error">Incorrect access code.</p>}<form action={openPrivateCase} className="stack"><input type="hidden" name="reference" value={reference}/><input type="hidden" name="role" value="requester"/><label>Private requester code<input name="accessCode" type="password" required/></label><button className="button">Review community offers</button></form></section></div>}const {data}=await db.from("responder_offers").select("public_reference,responder_name_encrypted,help_description_encrypted,eta_minutes,people_coming,has_vehicle,status,created_at").eq("request_id",request.id).order("created_at",{ascending:true});const offers=(data??[]) as Offer[];const protector=new AesGcmSensitiveDataProtector(env.DATA_ENCRYPTION_KEY!,env.PHONE_HASH_KEY!);return <div className="container stack"><header><p className="reference">{reference}</p><h1>Community offers</h1><p>Your phone number and exact location remain hidden until you accept an offer.</p></header>{offers.map(offer=><article className="card stack" key={offer.public_reference}><div className="request-top"><h2>{protector.decrypt(offer.responder_name_encrypted)}</h2><span className="status">{offer.status}</span></div><p>{protector.decrypt(offer.help_description_encrypted)}</p><p><strong>ETA:</strong> {offer.eta_minutes} minutes · <strong>People:</strong> {offer.people_coming} · <strong>Vehicle:</strong> {offer.has_vehicle?"Yes":"No"}</p>{offer.status==="OFFERED"&&<form action={acceptOffer}><input type="hidden" name="reference" value={reference}/><input type="hidden" name="offerReference" value={offer.public_reference}/><button className="button">Accept this help</button></form>}</article>)}{offers.length===0&&<section className="card"><h2>No offers yet</h2><p>Keep this page bookmarked and check again later.</p></section>}</div>}
