begin;
create extension if not exists postgis;
create extension if not exists pgcrypto;
create type public.app_role as enum ('CALL_CENTRE_OPERATOR','VOLUNTEER','VILLAGE_COORDINATOR','NGO_COORDINATOR','DISTRICT_COORDINATOR','ORG_ADMIN','PLATFORM_ADMIN');
create type public.request_status as enum ('NEW','UNDER_REVIEW','CALLBACK_REQUIRED','VERIFIED','UNABLE_TO_VERIFY','PRIORITISED','ORGANISATION_ASSIGNED','VOLUNTEER_ASSIGNED','ACCEPTED','EN_ROUTE','ON_SITE','ASSISTANCE_DELIVERED','VERIFICATION_PENDING','RESOLVED','REOPENED','DUPLICATE','CANCELLED','REQUESTER_UNREACHABLE','REFERRED_TO_AUTHORITY');
create type public.priority_level as enum ('P0_CRITICAL','P1_HIGH','P2_ESSENTIAL','P3_RECOVERY');
create type public.volunteer_state as enum ('PENDING','UNDER_REVIEW','VERIFIED','SUSPENDED','REJECTED','EXPIRED');
create type public.assignment_status as enum ('PROPOSED','ASSIGNED','ACCEPTED','DECLINED','EN_ROUTE','ON_SITE','ASSISTANCE_DELIVERED','VERIFICATION_PENDING','COMPLETED','FAILED','CANCELLED');
create table public.districts(id uuid primary key default gen_random_uuid(),name_en text not null unique,name_as text,created_at timestamptz not null default now());
create table public.villages(id uuid primary key default gen_random_uuid(),district_id uuid not null references public.districts, name text not null, pilot_seed boolean not null default false, created_at timestamptz not null default now(),unique(district_id,name));
create table public.profiles(id uuid primary key references auth.users on delete cascade,display_name text not null,phone_encrypted text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.roles(id uuid primary key default gen_random_uuid(),code public.app_role not null unique,description text not null);
create table public.permissions(id uuid primary key default gen_random_uuid(),code text not null unique,description text not null);
create table public.organisations(id uuid primary key default gen_random_uuid(),name text not null,verified boolean not null default false,created_at timestamptz not null default now(),deleted_at timestamptz);
create table public.organisation_members(organisation_id uuid references public.organisations,user_id uuid references public.profiles,role public.app_role not null,district_id uuid references public.districts,active boolean not null default true,created_at timestamptz not null default now(),primary key(organisation_id,user_id));
create table public.response_clusters(id uuid primary key default gen_random_uuid(),organisation_id uuid references public.organisations,district_id uuid references public.districts,name text not null,created_at timestamptz not null default now());
create table public.volunteers(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles,organisation_id uuid references public.organisations,district_id uuid not null references public.districts,state public.volunteer_state not null default 'PENDING',base_location geography(point,4326),max_travel_km numeric(6,2),identity_private_path text,consented_at timestamptz,code_accepted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.volunteer_skills(volunteer_id uuid references public.volunteers on delete cascade,skill text not null,verified boolean not null default false,primary key(volunteer_id,skill));
create table public.volunteer_resources(volunteer_id uuid references public.volunteers on delete cascade,resource text not null,available boolean not null default true,primary key(volunteer_id,resource));
create table public.volunteer_availability(id uuid primary key default gen_random_uuid(),volunteer_id uuid not null references public.volunteers on delete cascade,starts_at timestamptz not null,ends_at timestamptz not null,check(ends_at>starts_at));
create table public.help_requests(id uuid primary key default gen_random_uuid(),public_reference text not null unique default ('FSA-'||upper(encode(gen_random_bytes(8),'hex'))),organisation_id uuid references public.organisations,district_id uuid not null references public.districts,village_id uuid references public.villages,category text not null,status public.request_status not null default 'NEW',confirmed_priority public.priority_level,original_language text not null default 'as-IN',requester_name_encrypted text not null,phone_hash text not null,phone_encrypted text not null,description_encrypted text not null,affected_people int not null check(affected_people>0),consented_at timestamptz not null,idempotency_key uuid not null unique,legal_hold boolean not null default false,retention_review_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz);
create table public.request_people(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests on delete cascade,children int not null default 0,elderly int not null default 0,pregnant_count int not null default 0,disabled_count int not null default 0);
create table public.request_vulnerabilities(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests on delete cascade,kind text not null,details_encrypted text);
create table public.request_locations(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests on delete cascade,exact_location geography(point,4326),location_source text not null default 'TEXT_ONLY' check(location_source in ('GPS','MANUAL_PIN','TEXT_ONLY')),accuracy_metres numeric,locality text not null,landmark text,consent_at timestamptz,created_at timestamptz not null default now(),check(exact_location is null or consent_at is not null));
create index request_locations_geo_idx on public.request_locations using gist(exact_location);
create index help_requests_queue_idx on public.help_requests(status,confirmed_priority,created_at);
create index help_requests_phone_idx on public.help_requests(phone_hash,created_at);
create table public.request_translations(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests on delete cascade,original_text_encrypted text not null,raw_transcript_encrypted text,corrected_transcript_encrypted text,confirmed_transcript_encrypted text,english_translation_encrypted text,provider text,model text,confidence numeric(5,4),review_status text not null default 'PENDING',reviewed_by uuid references public.profiles,reviewed_at timestamptz,created_at timestamptz not null default now());
create table public.request_audio(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests on delete cascade,private_path text not null,mime_type text not null,size_bytes int not null,delete_after timestamptz not null,created_at timestamptz not null default now());
create table public.request_status_history(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests,from_status public.request_status,to_status public.request_status not null,reason text not null,actor_id uuid references public.profiles,created_at timestamptz not null default now());
create table public.request_priority_history(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests,suggested public.priority_level,confirmed public.priority_level not null,reason text not null,actor_id uuid not null references public.profiles,created_at timestamptz not null default now());
create table public.request_relationships(id uuid primary key default gen_random_uuid(),request_id uuid references public.help_requests,related_request_id uuid references public.help_requests,kind text not null,justification text not null,actor_id uuid references public.profiles,created_at timestamptz not null default now(),check(request_id<>related_request_id));
create table public.assignments(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests,volunteer_id uuid not null references public.volunteers,organisation_id uuid not null references public.organisations,status public.assignment_status not null default 'PROPOSED',contact_authorised boolean not null default false,accepted_at timestamptz,created_at timestamptz not null default now());
create table public.assignment_status_history(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.assignments,status public.assignment_status not null,reason text,actor_id uuid references public.profiles,created_at timestamptz not null default now());
create table public.internal_comments(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests,organisation_id uuid not null references public.organisations,body_encrypted text not null,author_id uuid not null references public.profiles,created_at timestamptz not null default now());
create table public.public_updates(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests,message_as text,message_en text not null,created_by uuid references public.profiles,created_at timestamptz not null default now());
create table public.request_evidence(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.help_requests,private_path text not null,mime_type text not null,size_bytes int not null,delete_after timestamptz,created_at timestamptz not null default now());
create table public.relief_centres(id uuid primary key default gen_random_uuid(),organisation_id uuid references public.organisations,district_id uuid references public.districts,village_id uuid references public.villages,name text not null,location geography(point,4326),capacity int,current_occupancy int,public_contact_enabled boolean not null default false,contact_encrypted text,facilities jsonb not null default '{}',last_verified_at timestamptz,created_at timestamptz not null default now());
create table public.inventory_items(id uuid primary key default gen_random_uuid(),relief_centre_id uuid references public.relief_centres,category text not null,quantity numeric not null default 0,reserved numeric not null default 0,minimum_threshold numeric not null default 0,unit text not null,unique(relief_centre_id,category));
create table public.inventory_transactions(id uuid primary key default gen_random_uuid(),item_id uuid references public.inventory_items,kind text not null,quantity numeric not null,approved_by uuid references public.profiles,created_at timestamptz not null default now());
create table public.supply_requests(id uuid primary key default gen_random_uuid(),relief_centre_id uuid references public.relief_centres,category text not null,quantity numeric not null,status text not null default 'OPEN',created_at timestamptz not null default now());
create table public.deliveries(id uuid primary key default gen_random_uuid(),supply_request_id uuid references public.supply_requests,status text not null,delivered_at timestamptz,evidence_path text,created_at timestamptz not null default now());
create table public.escalation_records(id uuid primary key default gen_random_uuid(),request_id uuid references public.help_requests,authority text not null,official_reference text,actor_id uuid references public.profiles,created_at timestamptz not null default now());
create table public.emergency_contacts(id uuid primary key default gen_random_uuid(),district_id uuid references public.districts,kind text not null,number text not null,source text not null,last_verified_at timestamptz not null,public boolean not null default true,updated_at timestamptz not null default now());
create table public.audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles,organisation_id uuid references public.organisations,action text not null,entity_type text not null,entity_id uuid,metadata_safe jsonb not null default '{}',ip_hash text,created_at timestamptz not null default now());
create table public.blocked_entities(id uuid primary key default gen_random_uuid(),kind text not null,value_hash text not null,reason text not null,created_by uuid references public.profiles,expires_at timestamptz,created_at timestamptz not null default now(),unique(kind,value_hash));
create table public.provider_health_events(id uuid primary key default gen_random_uuid(),provider text not null,operation text not null,status text not null,error_type text,retry_count int not null default 0,processing_time_ms int,created_at timestamptz not null default now());
create or replace function public.submit_help_request(payload jsonb) returns table(id uuid,public_reference text) language plpgsql security definer set search_path=public as $$
declare v_request_id uuid; v_request_reference text;
begin
  if payload->>'idempotency_key' is null then raise exception 'idempotency key required'; end if;
  select h.id,h.public_reference into v_request_id,v_request_reference from public.help_requests h where h.idempotency_key=(payload->>'idempotency_key')::uuid;
  if v_request_id is not null then return query select v_request_id,v_request_reference; return; end if;
  insert into public.help_requests(district_id,category,original_language,requester_name_encrypted,phone_hash,phone_encrypted,description_encrypted,affected_people,consented_at,idempotency_key)
  values((payload->>'district_id')::uuid,payload->>'category',payload->>'original_language',payload->>'requester_name_encrypted',payload->>'phone_hash',payload->>'phone_encrypted',payload->>'description_encrypted',(payload->>'affected_people')::int,(payload->>'consented_at')::timestamptz,(payload->>'idempotency_key')::uuid)
  returning help_requests.id,help_requests.public_reference into v_request_id,v_request_reference;
  insert into public.request_people(request_id,children,elderly) values(v_request_id,coalesce((payload->>'children')::int,0),coalesce((payload->>'elderly')::int,0));
  insert into public.request_locations(request_id,exact_location,location_source,accuracy_metres,locality,landmark,consent_at) values(v_request_id,case when payload->>'latitude' is not null and payload->>'longitude' is not null then ST_SetSRID(ST_MakePoint((payload->>'longitude')::double precision,(payload->>'latitude')::double precision),4326)::geography else null end,coalesce(payload->>'location_source','TEXT_ONLY'),nullif(payload->>'location_accuracy_metres','')::numeric,payload->>'locality',payload->>'landmark',nullif(payload->>'location_consent_at','')::timestamptz);
  insert into public.request_vulnerabilities(request_id,kind) select v_request_id,kind from (values
    ('MEDICAL_EMERGENCY',coalesce((payload->>'medical_emergency')::boolean,false)),
    ('IMMEDIATE_DANGER',coalesce((payload->>'immediate_danger')::boolean,false)),
    ('EVACUATION_REQUIRED',coalesce((payload->>'evacuation_required')::boolean,false))) flags(kind,active) where active;
  insert into public.request_status_history(request_id,to_status,reason) values(v_request_id,'NEW','Public intake accepted');
  return query select v_request_id,v_request_reference;
end$$;
revoke all on function public.submit_help_request(jsonb) from public,anon,authenticated;
grant execute on function public.submit_help_request(jsonb) to service_role;
alter table public.audit_events enable row level security;
create or replace function public.prevent_audit_mutation() returns trigger language plpgsql as $$begin raise exception 'audit events are immutable';end$$;
create trigger audit_immutable before update or delete on public.audit_events for each row execute function public.prevent_audit_mutation();
do $$declare t text;begin foreach t in array array['districts','villages','profiles','roles','permissions','organisations','organisation_members','response_clusters','volunteers','volunteer_skills','volunteer_resources','volunteer_availability','help_requests','request_people','request_vulnerabilities','request_locations','request_translations','request_audio','request_status_history','request_priority_history','request_relationships','assignments','assignment_status_history','internal_comments','public_updates','request_evidence','relief_centres','inventory_items','inventory_transactions','supply_requests','deliveries','escalation_records','emergency_contacts','blocked_entities','provider_health_events'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy "public district read" on public.districts for select using(true);
create policy "public village read" on public.villages for select using(true);
create policy "own profile read" on public.profiles for select to authenticated using(id=auth.uid());
create policy "verified volunteer own record" on public.volunteers for select to authenticated using(profile_id=auth.uid());
create policy "assigned volunteer assignment" on public.assignments for select to authenticated using(exists(select 1 from public.volunteers v where v.id=volunteer_id and v.profile_id=auth.uid() and v.state='VERIFIED'));
create policy "public safe updates" on public.public_updates for select using(true);
commit;
