"use server";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {revalidatePath} from "next/cache";
import {createClient} from "@supabase/supabase-js";
import {ORGANISER_COOKIE,isOrganiserAuthenticated,sessionValue,validAccessKey} from "@/lib/organiser-auth";
import {serverEnv} from "@/lib/env";

const statuses=["NEW","UNDER_REVIEW","CALLBACK_REQUIRED","VERIFIED","PRIORITISED","ORGANISATION_ASSIGNED","VOLUNTEER_ASSIGNED","ACCEPTED","EN_ROUTE","ON_SITE","ASSISTANCE_DELIVERED","RESOLVED","CANCELLED","REQUESTER_UNREACHABLE","REFERRED_TO_AUTHORITY"] as const;
export async function login(formData:FormData){const key=String(formData.get("accessKey")??"");if(!validAccessKey(key))redirect("/organiser/login?error=1");(await cookies()).set(ORGANISER_COOKIE,sessionValue(),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:60*60*8});redirect("/organiser")}
export async function logout(){(await cookies()).delete(ORGANISER_COOKIE);redirect("/organiser/login")}
export async function updateRequestStatus(formData:FormData){if(!await isOrganiserAuthenticated())redirect("/organiser/login");const requestId=String(formData.get("requestId")??"");const nextStatus=String(formData.get("status")??"");if(!/^[0-9a-f-]{36}$/i.test(requestId)||!statuses.includes(nextStatus as typeof statuses[number]))throw new Error("Invalid status update");const env=serverEnv();if(!env.NEXT_PUBLIC_SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)throw new Error("Supabase is not configured");const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});const {data:current,error:readError}=await db.from("help_requests").select("status").eq("id",requestId).single();if(readError||!current)throw new Error("Request not found");if(current.status!==nextStatus){const {error:updateError}=await db.from("help_requests").update({status:nextStatus,updated_at:new Date().toISOString(),closed_at:nextStatus==="RESOLVED"?new Date().toISOString():null}).eq("id",requestId);if(updateError)throw new Error("Status update failed");const {error:historyError}=await db.from("request_status_history").insert({request_id:requestId,from_status:current.status,to_status:nextStatus,reason:"Updated from organiser dashboard"});if(historyError)throw new Error("Status history update failed")}revalidatePath("/organiser");}
